### ISSUE TITLE
[discussion] about fs.c code on Windows

### ISSUE THREAD

**Issue by vtorri** [lexborisov/lexbor#10]
On Windows, I use the Win32 API and the GetFileAttributes() function. The list of file types is there : 

https://docs.microsoft.com/fr-fr/windows/desktop/FileIO/file-attribute-constants

would it be possible to add the missing attributes to lexbor_fs_file_type_t ?

of course, documentation should provided so that specific attributes are for Windows.

**Comment by lexborisov** [comment]
Yes, of course you can. But mark them as win: `LEXBOR_FS_FILE_TYPE_WIN_...`

**Comment by vtorri** [comment]
finally, these are not relevant, closing
