### ISSUE TITLE
cc missing (MSYS2)

### ISSUE THREAD

**Issue by vtorri** [lexborisov/lexbor#6]
With the gcc package of MSYS2, cc is missing

maybe cc should be defined to gcc in Makefile if it is not present

**Comment by lexborisov** [comment]
CMAKE will solve all the problems! 😃

**Comment by vtorri** [comment]
same for autotools or meson :-)

**Comment by vtorri** [comment]
autotools code that create the DLL here

https://github.com/vtorri/lexbor/commit/18e53b8c042ec5f243b63bf0777c6d5f302fb420

steps : 
1) autoreconf -vif
2) ./configure
3) make -j

i've managed only the library

there are some missing points, like which headers must be installed for the API

please review and tell me what you think about the build system

note : i've added a Windows port of perf.c in this branch. See #7

**Comment by vtorri** [comment]
cmake is chosen, close issue
