### ISSUE TITLE
usefulness of dev/xcode directory

### ISSUE THREAD

**Issue by vtorri** [lexborisov/lexbor#8]
as cmake is used and as cmake can create xcode project files, is dev/xcode directory useful ?

**Comment by lexborisov** [comment]
Hi!
Yes, it is useful. XCode project in the directory is not for building a library. It is exclusively for development. The project builds an [executable file](https://github.com/lexborisov/lexbor/blob/master/dev/xcode/lexbor.c). Simply put, I'm developing in XCode :)
